name: Host
on:
  push:
    branches:
      - main
    paths:
      - 'hello/**'
defaults:
  run:
    working-directory: hello
jobs:
  Build-App-Steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
