name: Host
on:
  push:
    branches:
      - main
    paths:
      - 'hello/**'
defaults:
  run:
    working-directory: hello
jobs:
  Run-super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Run super linter
      - uses: github/super-linter@v3

  Build-App-Steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
